### ISSUE TITLE
Use server-names of users in result output instead of account-names

### ISSUE THREAD

**Issue by MaracuyaQ** [matnad/pollmaster#14] opened 2019-03-06 13:47 UTC
At the moment, the results for non-anonymous votes use the account names of the users who participated in the vote. On a server, often users have different names, so that they can be easily recognized. If Pollmaster used the names from the server instead of the accounts, that would make understanding poll results easier.

**Comment by matnad** [comment] 2019-03-21 14:21
This will be implemented with the next update

**Comment by matnad** [comment] 2019-03-23 11:50
#16  should implement this. Closing the issue.
Please open a new issue if it is not behaving as intended.

**Closed by matnad** 2019-03-23 11:50 UTC
